basegraphdelegate.cpp:            qDebug() << item->boundingRect2();
basegraphdelegate.cpp:            qDebug() << item->boundingRect2();
decomposer.cpp:        qDebug() << "t1";
decomposer.cpp:            qDebug() << "t2";
decomposer.cpp:            qDebug() << "t3";
graphmodel.cpp:        qDebug() << "Something is fucking wrong";
graphmodel.cpp:                qDebug() << "average_edge : "<<edge_center;
graphmodelgraphicsitem.cpp:            qDebug() << "wtf";
graphmodelgraphicsitem.cpp:                qDebug() << "something wrong";
graphmodelgraphicsitem.cpp:    qDebug() << "setGridRotate2";
gzzcalculatorjob.cpp:        qDebug() <<m_calc->getPoly().toHTML3();
gzzpolynomialcalculator.cpp:            qDebug() << t;
gzzpolynomialcalculator.cpp:            qDebug() << t;
gzzpolynomialcalculator.cpp:                qDebug() << t;
main.cpp:        qDebug() << "level: " << level << "  " << real->pos();
neightborlist.cpp:            qDebug() << "Too many neighbors in NeighborList class";
neightborlist.cpp:            qDebug() << "Too many neighbors in NeighborList class";
widthcombinecommand.cpp:        qDebug() << "someting happened";
zzpolynomialcalculator.cpp:            qDebug() << t;
zzpolynomialcalculator.cpp:            qDebug() << t;
zzpolynomialcalculator.cpp:                qDebug() << t;
